### ISSUE TITLE
It doesn't seem to accept YouTube videos anymore

### ISSUE THREAD

**Issue by HNT1807** [hayabhay/whisper-ui#11]
Thank you so much for the amazing work!

I'm unable to get a transcription for YouTube videos, I always get "Selected video/audio is could not be located.." no matter what video I load in

**Comment by SiddiqueFarhan** [comment]
same happening with me as well

**Comment by hayabhay** [comment]
Thanks for flagging and apologies! I've largely been busy with other things. I'll take a look at this over the weekend and update it.

**Comment by HNT1807** [comment]
No problem at all, what you built is amazing!! If there is a way to drag and drop files + getting files from an URL (like from a BOX.com link for example), it would be REAAALLLLYYY COOL!

**Comment by hayabhay** [comment]
Apologies for the delay. This should now be fixed. If this happens again, please raise another issue (#13)
