### ISSUE TITLE
the app not working, getting issues 

### ISSUE THREAD

**Issue by akashAD98** [hayabhay/whisper-ui#14]
im using windows 10 & installed all requirements, & got this issue.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/62583018/217168274-f88a4958-4fec-4eda-82d6-73572faa0025.png">

**Comment by hayabhay** [comment]
This looks like an issue with Whisper. Try `import whisper` on a python interpreter within that environment and check to verify. From the looks of it, conda env might be missing some dependencies.

**Comment by akashAD98** [comment]
issue solved by creating new anaconda env ,with python =3.8
