### ISSUE TITLE
Problem after update.

### ISSUE THREAD

**Issue by Cate9021** [hayabhay/whisper-ui#15]
![filenotfound](https://user-images.githubusercontent.com/116907383/217296129-56b76960-92a5-4b73-9c8e-4770cc50cf82.png)

**Comment by hayabhay** [comment]
Interesting. Could you provide more context around this. 
1. What was the format of the file uploaded?
2. What is the Python Env?

**Comment by Cate9021** [comment]
what i test for format is : youtube link, wav, mp4 so, I don't think is file format problem.
I use anaconda, here is the environment.yml:
`name: whisper
channels:
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - anyio=3.5.0=py310haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py310haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - colorama=0.4.6=py310haa95532_0
  - comm=0.1.2=py310haa95532_0
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - idna=3.4=py310haa95532_0
  - ipykernel=6.19.2=py310h9909e9c_0
  - ipython=8.8.0=py310haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py310haa95532_1
  - jinja2=3.1.2=py310haa95532_0
  - jsonschema=4.16.0=py310haa95532_0
  - jupyter_client=7.4.8=py310haa95532_0
  - jupyter_core=5.1.1=py310haa95532_0
  - jupyter_server=1.23.4=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - libsodium=1.0.18=h62dcd97_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - lxml=4.9.1=py310h1985fb9_0
  - m2w64-bwidget=1.9.10=2
  - m2w64-bzip2=1.0.6=6
  - m2w64-expat=2.1.1=2
  - m2w64-fftw=3.3.4=6
  - m2w64-flac=1.3.1=3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-gsl=2.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libjpeg-turbo=1.4.2=3
  - m2w64-libogg=1.3.2=3
  - m2w64-libpng=1.6.21=2
  - m2w64-libsndfile=1.0.26=2
  - m2w64-libsodium=1.0.10=2
  - m2w64-libtiff=4.0.6=2
  - m2w64-libvorbis=1.3.5=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-libxml2=2.9.3=4
  - m2w64-mpfr=3.1.4=4
  - m2w64-openblas=0.2.19=1
  - m2w64-pcre=8.38=2
  - m2w64-speex=1.2rc2=3
  - m2w64-speexdsp=1.2rc3=3
  - m2w64-tcl=8.6.5=3
  - m2w64-tk=8.6.5=3
  - m2w64-tktable=2.10=5
  - m2w64-wineditline=2.101=5
  - m2w64-xz=5.2.2=2
  - m2w64-zeromq=4.1.4=2
  - m2w64-zlib=1.2.8=10
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mistune=0.8.4=py310h2bbff1b_1000
  - msys2-conda-epoch=20160418=1
  - nbclassic=0.4.8=py310haa95532_0
  - nbclient=0.5.13=py310haa95532_0
  - nbconvert=6.5.4=py310haa95532_0
  - nbformat=5.7.0=py310haa95532_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - notebook=6.5.2=py310haa95532_0
  - notebook-shim=0.2.2=py310haa95532_0
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=22.0=py310haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.3.1=py310haa95532_0
  - platformdirs=2.5.2=py310haa95532_0
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt-toolkit=3.0.36=py310haa95532_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py310h2bbff1b_0
  - python=3.10.9=h966fe2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - pywin32=305=py310h2bbff1b_0
  - pywinpty=2.0.2=py310h5da7b33_0
  - pyzmq=23.2.0=py310hd77b12b_0
  - r-askpass=1.0=r36_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-backports=1.1.4=r36h6115d3f_0
  - r-base=3.6.1=hf18239d_1
  - r-base64enc=0.1_3=r36h6115d3f_4
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-boot=1.3_20=r36h6115d3f_0
  - r-broom=0.5.2=r36h6115d3f_0
  - r-callr=3.2.0=r36h6115d3f_0
  - r-caret=6.0_83=r36h6115d3f_0
  - r-cellranger=1.1.0=r36h6115d3f_0
  - r-class=7.3_15=r36h6115d3f_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-clipr=0.6.0=r36h6115d3f_0
  - r-cluster=2.0.8=r36h6115d3f_0
  - r-codetools=0.2_16=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h6115d3f_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-curl=3.3=r36h6115d3f_0
  - r-data.table=1.12.2=r36h6115d3f_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h6115d3f_0
  - r-dplyr=0.8.0.1=r36h6115d3f_0
  - r-ellipsis=0.1.0=r36h6115d3f_0
  - r-essentials=3.6.0=r36_0
  - r-evaluate=0.13=r36h6115d3f_0
  - r-fansi=0.4.0=r36h6115d3f_0
  - r-forcats=0.4.0=r36h6115d3f_0
  - r-foreach=1.4.4=r36h6115d3f_0
  - r-foreign=0.8_71=r36h6115d3f_0
  - r-formatr=1.6=r36h6115d3f_0
  - r-fs=1.2.7=r36h6115d3f_0
  - r-generics=0.0.2=r36h6115d3f_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-glmnet=2.0_16=r36h6115d3f_0
  - r-glue=1.3.1=r36h6115d3f_0
  - r-gower=0.2.0=r36h6115d3f_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-haven=2.1.0=r36h6115d3f_0
  - r-hexbin=1.27.2=r36h6115d3f_0
  - r-highr=0.8=r36h6115d3f_0
  - r-hms=0.4.2=r36h6115d3f_0
  - r-htmltools=0.3.6=r36h6115d3f_0
  - r-htmlwidgets=1.3=r36h6115d3f_0
  - r-httpuv=1.5.1=r36h6115d3f_0
  - r-httr=1.4.0=r36h6115d3f_0
  - r-ipred=0.9_8=r36h6115d3f_0
  - r-irdisplay=0.7.0=r36h6115d3f_0
  - r-irkernel=0.8.15=r36_0
  - r-iterators=1.0.10=r36h6115d3f_0
  - r-jsonlite=1.6=r36h6115d3f_0
  - r-kernsmooth=2.23_15=r36h6115d3f_4
  - r-knitr=1.22=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_4
  - r-later=0.8.0=r36h6115d3f_0
  - r-lattice=0.20_38=r36h6115d3f_0
  - r-lava=1.6.5=r36h6115d3f_0
  - r-lazyeval=0.2.2=r36h6115d3f_0
  - r-lubridate=1.7.4=r36h6115d3f_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-maps=3.3.0=r36h6115d3f_0
  - r-markdown=0.9=r36h6115d3f_0
  - r-mass=7.3_51.3=r36h6115d3f_0
  - r-matrix=1.2_17=r36h6115d3f_0
  - r-mgcv=1.8_28=r36h6115d3f_0
  - r-mime=0.6=r36h6115d3f_0
  - r-modelmetrics=1.2.2=r36h6115d3f_0
  - r-modelr=0.1.4=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-nlme=3.1_139=r36h6115d3f_0
  - r-nnet=7.3_12=r36h6115d3f_0
  - r-numderiv=2016.8_1=r36h6115d3f_0
  - r-openssl=1.3=r36h6115d3f_0
  - r-pbdzmq=0.3_3=r36h6115d3f_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.4=r36h6115d3f_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-processx=3.3.0=r36h6115d3f_0
  - r-prodlim=2018.04.18=r36h6115d3f_0
  - r-progress=1.2.0=r36h6115d3f_0
  - r-promises=1.0.1=r36h6115d3f_0
  - r-ps=1.3.0=r36h6115d3f_0
  - r-purrr=0.3.2=r36h6115d3f_0
  - r-quantmod=0.4_14=r36h6115d3f_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-randomforest=4.6_14=r36h6115d3f_0
  - r-rbokeh=0.6.3=r36_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h6115d3f_0
  - r-rcpproll=0.3.0=r36h6115d3f_0
  - r-readr=1.3.1=r36h6115d3f_0
  - r-readxl=1.3.1=r36h6115d3f_0
  - r-recipes=0.1.5=r36h6115d3f_0
  - r-recommended=3.6.0=r36_0
  - r-rematch=1.0.1=r36h6115d3f_0
  - r-repr=0.19.2=r36h6115d3f_0
  - r-reprex=0.2.1=r36h6115d3f_0
  - r-reshape2=1.4.3=r36h6115d3f_0
  - r-rlang=0.3.4=r36h6115d3f_0
  - r-rmarkdown=1.12=r36h6115d3f_0
  - r-rpart=4.1_15=r36h6115d3f_0
  - r-rstudioapi=0.10=r36h6115d3f_0
  - r-rvest=0.3.3=r36h6115d3f_0
  - r-scales=1.0.0=r36h6115d3f_0
  - r-selectr=0.4_1=r36h6115d3f_0
  - r-shiny=1.3.2=r36h6115d3f_0
  - r-sourcetools=0.1.7=r36h6115d3f_0
  - r-spatial=7.3_11=r36h6115d3f_4
  - r-squarem=2017.10_1=r36h6115d3f_0
  - r-stringi=1.4.3=r36h6115d3f_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-survival=2.44_1.1=r36h6115d3f_0
  - r-sys=3.2=r36h6115d3f_0
  - r-tibble=2.1.1=r36h6115d3f_0
  - r-tidyr=0.8.3=r36h6115d3f_0
  - r-tidyselect=0.2.5=r36h6115d3f_0
  - r-tidyverse=1.2.1=r36h6115d3f_0
  - r-timedate=3043.102=r36h6115d3f_0
  - r-tinytex=0.12=r36h6115d3f_0
  - r-ttr=0.23_4=r36h6115d3f_0
  - r-utf8=1.1.4=r36h6115d3f_0
  - r-uuid=0.1_2=r36h6115d3f_4
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-whisker=0.3_2=r36h6115d3f_4
  - r-withr=2.1.2=r36h6115d3f_0
  - r-xfun=0.6=r36h6115d3f_0
  - r-xml2=1.2.0=r36h6115d3f_0
  - r-xtable=1.8_4=r36h6115d3f_0
  - r-xts=0.11_2=r36h6115d3f_0
  - r-yaml=2.2.0=r36h6115d3f_0
  - r-zoo=1.8_5=r36h6115d3f_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py310haa95532_1
  - soupsieve=2.3.2.post1=py310haa95532_0
  - sqlite=3.40.1=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py310haa95532_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py310h2bbff1b_0
  - traitlets=5.7.1=py310haa95532_0
  - typing-extensions=4.4.0=py310haa95532_0
  - typing_extensions=4.4.0=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=0.58.0=py310haa95532_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - winpty=0.4.3=4
  - xz=5.2.10=h8cc25b3_1
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - altair==4.2.2
    - blinker==1.5
    - cachetools==5.3.0
    - charset-normalizer==3.0.1
    - click==8.1.3
    - ffmpeg==1.4
    - ffmpeg-python==0.2.0
    - filelock==3.9.0
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.30
    - greenlet==2.0.2
    - huggingface-hub==0.12.0
    - importlib-metadata==6.0.0
    - markdown-it-py==2.1.0
    - mdurl==0.1.2
    - more-itertools==9.0.0
    - numpy==1.24.2
    - openai-whisper==20230124
    - pandas==1.5.3
    - protobuf==3.20.3
    - pyarrow==11.0.0
    - pydeck==0.8.0
    - pygments==2.14.0
    - pympler==1.0.1
    - pytube==12.1.2
    - pytz==2022.7.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - rich==13.3.1
    - semver==2.13.0
    - smmap==5.0.0
    - sqlalchemy==2.0.0
    - streamlit==1.17.0
    - tokenizers==0.13.2
    - toml==0.10.2
    - toolz==0.12.0
    - torch==1.13.1
    - tqdm==4.64.1
    - transformers==4.26.0
    - tzdata==2022.7
    - tzlocal==4.2
    - urllib3==1.26.14
    - validators==0.20.0
    - watchdog==2.2.1
    - zipp==3.12.1
prefix: C:\Users\PCUL\.conda\envs\whisper
`
I do create new environment for this update, and I use Python 3.10.9. I some how have problem to get streamlit to work in python 3.11.0.

**Comment by Cate9021** [comment]
here is the log that occur, it may help to figure out what's wrong:
`2023-02-08 20:02:01,326 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-02-08 20:02:01.326 BEGIN (implicit)
2023-02-08 20:02:01,327 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("media")
2023-02-08 20:02:01.327 PRAGMA main.table_info("media")
2023-02-08 20:02:01,327 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-02-08 20:02:01.327 [raw sql] ()
2023-02-08 20:02:01,328 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("transcript")
2023-02-08 20:02:01.328 PRAGMA main.table_info("transcript")
2023-02-08 20:02:01,328 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-02-08 20:02:01.328 [raw sql] ()
2023-02-08 20:02:01,328 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("segment")
2023-02-08 20:02:01.328 PRAGMA main.table_info("segment")
2023-02-08 20:02:01,328 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-02-08 20:02:01.328 [raw sql] ()
2023-02-08 20:02:01,329 INFO sqlalchemy.engine.Engine COMMIT
2023-02-08 20:02:01.329 COMMIT
2023-02-08 20:02:01,736 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-02-08 20:02:01.736 BEGIN (implicit)
2023-02-08 20:02:01,739 INFO sqlalchemy.engine.Engine SELECT media.source_type AS media_source_type, media.source_name AS media_source_name, media.source_link AS media_source_link, media.filepath AS media_filepath, media.duration AS media_duration, media.id AS media_id, media.created AS media_created, media.updated AS media_updated
FROM media JOIN transcript ON media.id = transcript.media_id ORDER BY media.created DESC
 LIMIT ? OFFSET ?
2023-02-08 20:02:01.739 SELECT media.source_type AS media_source_type, media.source_name AS media_source_name, media.source_link AS media_source_link, media.filepath AS media_filepath, media.duration AS media_duration, media.id AS media_id, media.created AS media_created, media.updated AS media_updated
FROM media JOIN transcript ON media.id = transcript.media_id ORDER BY media.created DESC
 LIMIT ? OFFSET ?
2023-02-08 20:02:01,740 INFO sqlalchemy.engine.Engine [generated in 0.00055s] (10, 0)
2023-02-08 20:02:01.740 [generated in 0.00055s] (10, 0)
2023-02-08 20:02:12,361 INFO sqlalchemy.engine.Engine SELECT media.source_type AS media_source_type, media.source_name AS media_source_name, media.source_link AS media_source_link, media.filepath AS media_filepath, media.duration AS media_duration, media.id AS media_id, media.created AS media_created, media.updated AS media_updated
FROM media JOIN transcript ON media.id = transcript.media_id ORDER BY media.created DESC
 LIMIT ? OFFSET ?
2023-02-08 20:02:12.361 SELECT media.source_type AS media_source_type, media.source_name AS media_source_name, media.source_link AS media_source_link, media.filepath AS media_filepath, media.duration AS media_duration, media.id AS media_id, media.created AS media_created, media.updated AS media_updated
FROM media JOIN transcript ON media.id = transcript.media_id ORDER BY media.created DESC
 LIMIT ? OFFSET ?
2023-02-08 20:02:12,363 INFO sqlalchemy.engine.Engine [cached since 10.62s ago] (10, 0)
2023-02-08 20:02:12.363 [cached since 10.62s ago] (10, 0)
2023-02-08 20:02:15,336 INFO sqlalchemy.engine.Engine SELECT media.source_type AS media_source_type, media.source_name AS media_source_name, media.source_link AS media_source_link, media.filepath AS media_filepath, media.duration AS media_duration, media.id AS media_id, media.created AS media_created, media.updated AS media_updated
FROM media JOIN transcript ON media.id = transcript.media_id ORDER BY media.created DESC
 LIMIT ? OFFSET ?
2023-02-08 20:02:15.336 SELECT media.source_type AS media_source_type, media.source_name AS media_source_name, media.source_link AS media_source_link, media.filepath AS media_filepath, media.duration AS media_duration, media.id AS media_id, media.created AS media_created, media.updated AS media_updated
FROM media JOIN transcript ON media.id = transcript.media_id ORDER BY media.created DESC
 LIMIT ? OFFSET ?
2023-02-08 20:02:15,336 INFO sqlalchemy.engine.Engine [cached since 13.6s ago] (10, 0)
2023-02-08 20:02:15.336 [cached since 13.6s ago] (10, 0)
2023-02-08 20:02:24,441 INFO sqlalchemy.engine.Engine SELECT media.source_type AS media_source_type, media.source_name AS media_source_name, media.source_link AS media_source_link, media.filepath AS media_filepath, media.duration AS media_duration, media.id AS media_id, media.created AS media_created, media.updated AS media_updated
FROM media JOIN transcript ON media.id = transcript.media_id ORDER BY media.created DESC
 LIMIT ? OFFSET ?
2023-02-08 20:02:24.441 SELECT media.source_type AS media_source_type, media.source_name AS media_source_name, media.source_link AS media_source_link, media.filepath AS media_filepath, media.duration AS media_duration, media.id AS media_id, media.created AS media_created, media.updated AS media_updated
FROM media JOIN transcript ON media.id = transcript.media_id ORDER BY media.created DESC
 LIMIT ? OFFSET ?
2023-02-08 20:02:24,442 INFO sqlalchemy.engine.Engine [cached since 22.7s ago] (10, 0)
2023-02-08 20:02:24.442 [cached since 22.7s ago] (10, 0)
C:\Users\PCUL\.conda\envs\whisper\lib\site-packages\whisper\transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
2023-02-08 20:02:49.533 Uncaught app exception`

**Comment by hayabhay** [comment]
I added an `environment.yml` file. Please try creating a new conda environment with it to see if it helps. I couldn't reproduce the error on my machine (Ubuntu) and I wonder if it is a Windows quirk. There was another windows related issue that was fixed as well so they may be related.

**Comment by Cate9021** [comment]
just tried it, turn out there have no windows ncurses.
![errorwhisper](https://user-images.githubusercontent.com/116907383/217673797-a492e3b0-6f8a-44a1-b50f-0f42c7fe1a06.png)

**Comment by hayabhay** [comment]
ah! I expected a new conda to install `ncurses` as well. 
For context, I installed it off a `miniconda` installation on Ubuntu 22.04

**Comment by Cate9021** [comment]
One more that can't be install to windows.
would like to know do you have intent to make this work on windows?
![image](https://user-images.githubusercontent.com/116907383/217759237-0f704155-e49f-423f-b7c3-64175984e91f.png)
then maybe I can help you figure out one by one when I'm free, however if you don't have the intent to make this work on window, then I don't want to bother you with this.
I can totally understand the pain to make different platform work.

**Comment by hayabhay** [comment]
This does seem confusing since other Issues raised have this running on Windows successfully (see #16). So I'm unsure if this is Windows specifically or some dependency with Python.

Since the issue is primarily with Whisper, one way is to see if you can get Whisper working directly [from their repo](https://github.com/openai/whisper). If this works, I'm guessing this repo should work too. 

The code in this repo is very skinny and uses mostly platform independent code (there may be some bugs like with #16). Since I don't have a windows machine, it is hard for me to reproduce but I'm happy to accept PRs if there is any specific dependency that needs to be updated to support windows.

**Comment by Cate9021** [comment]
Finally make it work!
Problem solved.

**Comment by hayabhay** [comment]
Thanks for the PR! Was it `ffmpeg` or were there issues with the emoji in the filename?

**Comment by Cate9021** [comment]
it was: ffmpeg, pip install setuptools-rust.
from my testing, emoji do cause issues if not going through conda env, but it's okay in conda.
