### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by schklom** [hayabhay/whisper-ui#23]
A Docker image would be great to make it easier to deploy.

A draft for the quantized version's Dockerfile could look like
```dockerfile
FROM python:latest
COPY . .
RUN apt-get update
RUN apt-get install -y ffmpeg
RUN pip install streamlit
RUN pip install setuptools-rust
# RUN pip install git+https://github.com/openai/whisper.git
RUN pip install git+https://github.com/MiscellaneousStuff/whisper.git

ENV PATH="$HOME/.cargo/bin:$PATH"
EXPOSE 8501
VOLUME /data/.whisper_settings.json
CMD streamlit run app/01_🏠_Home.py
```

I'm trying to figure out what directory is used for the data.

Edit: `EXPOSE` instead of `PORT`

**Comment by hayabhay** [comment]
Good call. Will add a docker config.

Data folder gets created at the project root. You can change them as you see fit in the config file.

**Comment by rursache** [comment]
a published image would also be nice. you could setup github actions
