### ISSUE TITLE
Feature request - quick way to pause audio without losing spot in page?

### ISSUE THREAD

**Issue by yiek888** [hayabhay/whisper-ui#3]
Hey, really enjoying checking this so far, thanks for sharing it. 

I'm trying this out by reading along some transcripts for some YouTube videos and taking notes, and sometimes I have to pause to finish my note but I don't have an easy way of doing that without scrolling all the way up the page to the pause button on the audio player (I'm currently just using the trimmed audio player). But then after I pause, I have lost my spot in the page on the transcript. Any ideas for making pausing the audio player easier and letting me keep my spot on the page to make it easy to take notes?

Also another sneak request, in the terminal stdout logs I see the transcription timestamps in MM:SS.mmm format, but in the Streamlit UI it looks like the timestamps are only in seconds (so like 181.6s instead of 03:01.600). Any way to get the Streamlit UI timestamps format to minutes, seconds, millis?

**Comment by hayabhay** [comment]
Excellent call! Updating the UI and making it more usable is the first thing on my roadmap so I'll add this in over the weekend! Stay tuned!

**Comment by hayabhay** [comment]
Apologies for the delay but you should now be able to save the spot and navigate through segments and play the corresponding audio segment easily (ref #13)
