### ISSUE TITLE
Help. Still can't get it to run

### ISSUE THREAD

**Issue by psychomike** [hayabhay/whisper-ui#43]
![image](https://user-images.githubusercontent.com/2747352/235311566-d7a97f6f-f150-4a11-9e03-3520027b1fed.png)

**Comment by hayabhay** [comment]
This looks like a [bug with PyTube](https://github.com/pytube/pytube/issues/1597) and likely something with returned YouTube payload.

Will try to dig deeper in the next couple of days.

**Comment by yvangodard** [comment]
+1

**Comment by hayabhay** [comment]
Should be fixed with [this PR](https://github.com/hayabhay/whisper-ui/pull/46). Closing this for now. Please reopen if it persists.
