### ISSUE TITLE
Youtube translation issue

### ISSUE THREAD

**Issue by KamV1** [hayabhay/whisper-ui#44]
![Screenshot_6](https://user-images.githubusercontent.com/11591195/235343025-570eeea4-19a1-4b03-add0-6d51377aa0e0.jpg)

**Comment by Tobe2d** [comment]
+1

**Comment by hayabhay** [comment]
PyTube seems to be failing. Another issue is filed [here](https://github.com/hayabhay/whisper-ui/issues/43). Will dig deeper and try to fix it in the next couple of days.

**Comment by hayabhay** [comment]
Should be fixed with [this PR](https://github.com/hayabhay/whisper-ui/pull/46). Closing this for now. Please reopen if it persists.
