### ISSUE TITLE
Update to streamlit 1.20.0 or higher to avoid altair.vegalite.v4 module missing issue

### ISSUE THREAD

**Issue by ashledombos** [hayabhay/whisper-ui#49]
Hello,

when starting the app streamlit 1.18.1 I get this issue : 

    ModuleNotFoundError: No module named ‘altair.vegalite.v4

Following [this post](https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-altair-vegalite-v4/42921/6) I updated to streamlit 1.20.0 and it was fixed, so I kindly suggest to update the requirements accordingly.

Raphaël

**Comment by menelic** [comment]
this worked for me, did not install before, but with this change I got it to work, thanks!

**Comment by fromtoulouse** [comment]
you talk about :
(whisperUI) C:\WHisper-et-LLM\whisper-ui>streamlit run app/01_��_Home.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tv05\.conda\envs\whisperUI\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "C:\Users\tv05\.conda\envs\whisperUI\Lib\site-packages\streamlit\__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\Users\tv05\.conda\envs\whisperUI\Lib\site-packages\streamlit\delta_generator.py", line 43, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "C:\Users\tv05\.conda\envs\whisperUI\Lib\site-packages\streamlit\elements\arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

yes ?

**Comment by hayabhay** [comment]
I just merged a patch that should fix this.

**Comment by ashledombos** [comment]
> you talk about : (whisperUI) C:\WHisper-et-LLM\whisper-ui>streamlit run app/01_��_Home.py Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\tv05.conda\envs\whisperUI\Scripts\streamlit.exe__main__.py", line 4, in File "C:\Users\tv05.conda\envs\whisperUI\Lib\site-packages\streamlit__init__.py", line 55, in from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator File "C:\Users\tv05.conda\envs\whisperUI\Lib\site-packages\streamlit\delta_generator.py", line 43, in from streamlit.elements.arrow_altair import ArrowAltairMixin File "C:\Users\tv05.conda\envs\whisperUI\Lib\site-packages\streamlit\elements\arrow_altair.py", line 36, in from altair.vegalite.v4.api import Chart ModuleNotFoundError: No module named 'altair.vegalite.v4'
> 
> yes ?

Missed your reply, sorry. Yes indeed.
