### ISSUE TITLE
Feature request-Can it do Translation soon?

### ISSUE THREAD

**Issue by swankwc** [hayabhay/whisper-ui#5]
I have a need to update and translate a bunch of transcripts on a channel. Keep up the good work.

**Comment by hayabhay** [comment]
I'll be putting out a release this weekend with a large number of updates. This will include pulling entire channels/playlists & saving them to a database. Stay tuned!

**Comment by hayabhay** [comment]
Apologies for the delay but bulk transcription is now possible (per playlist) but will table translation for now. Will keep this open nonetheless (see #13)

**Comment by hayabhay** [comment]
Translation is now supported with #19
