### ISSUE TITLE
Found a bug when transcribe an uploaded files

### ISSUE THREAD

**Issue by Cate9021** [hayabhay/whisper-ui#7]
![bug](https://user-images.githubusercontent.com/116907383/198691822-fa9aae1a-d5ec-4b51-b02d-48298d14dc0c.png)

**Comment by hayabhay** [comment]
oops! Will fix!

**Comment by zanymuzik** [comment]
I was able to workaround by creating that directory manually

**Comment by lechatnieger** [comment]
Hi, i have the same problem, is there a way to create the folder from the web interface?

Thank you

**Comment by hayabhay** [comment]
Apologies for the delay. This should now be fixed. If this happens again, please raise another issue (#13)
