### ISSUE TITLE
Summarize Issue: IndexError: index out of range in self

### ISSUE THREAD

**Issue by Andreilys** [hayabhay/whisper-ui#9]
Getting this error when running Summarize

"Return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self"

<img width="1764" alt="Screenshot 2022-11-18 at 1 24 25 PM" src="https://user-images.githubusercontent.com/8299248/202805036-f6c9c9a9-4589-475a-a241-a0b7c0a8ab32.png">

**Comment by hayabhay** [comment]
Summarization is currently removed and will be integrated with GPT-3 in the next update and should fix this issue.
